[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

; 手动指定端口（根据下方排查结果替换为真实的 COM 号，如 COM3, COM5 等）
upload_port = COM8
monitor_port = COM8

board_build.partitions = huge_app.csv 

build_flags = 
    -D USE_NIMBLE
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    ; 设置为标准单连接，释放蓝牙内核内存
    -D CONFIG_BT_NIMBLE_MAX_CONNECTIONS=1

lib_deps =
    h2zero/NimBLE-Arduino @ 1.4.3
    t-vk/ESP32 BLE Mouse @ ^0.3.1
    adafruit/Adafruit SSD1306 @ ^2.5.17
    adafruit/Adafruit GFX Library @ ^1.12.6

lib_ignore = 
    BLE