[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

upload_port = COM5
monitor_port = COM5

board_build.partitions = huge_app.csv 

build_flags = 
    -D USE_NIMBLE
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    ; 🎯 修改为允许 2 个并发连接（1个给电脑鼠标，1个给手机App调参）
    -D CONFIG_BT_NIMBLE_MAX_CONNECTIONS=2

lib_deps =
    h2zero/NimBLE-Arduino @ 1.4.3
    t-vk/ESP32 BLE Mouse @ ^0.3.1
    adafruit/Adafruit SSD1306 @ ^2.5.17
    adafruit/Adafruit GFX Library @ ^1.12.6

lib_ignore = 
    BLE